blacklist = ["avante.nvim"]

[[session]]
name = "dagger_io ğŸš€"
path = "~/dagger/dagger.io"

[[session]]
name = "dagger ğŸ—¡ï¸"
path = "~/dagger/dagger"

[[session]]
name = "dotfiles ğŸ–¥ï¸"
path = "~/dotfiles"
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "facetrack ğŸ‘¤"
path = "~/code/gofacetrack"

[[session]]
name = "code ğŸ§‘â€ğŸ’»"
path = "~/code"
startup_command = "ls"
